// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwsioeneezgkqbkednj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d3Npb2VuZWV6Z2txYmtlZG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODQ1MzAsImV4cCI6MjA2ODg2MDUzMH0.P4fJbGPPFa46jgeKlRM4TepHQGsPgb_f-EtxFgsHdao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});